name: 问题反馈 / Bug report
title: "[BUG] "
description: 反馈你遇到的问题 / Report the issue you are experiencing
labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: |
        感谢您花时间填写这个 Bug 报告
  - type: checkboxes
    id: checkboxes
    attributes:
      label: 一些验证
      description: 在提交问题之前，请确保您完成以下操作
      options:
        - label: 请 **确保** 您已经查阅了 [GKD 官方文档](https://gkd.li)  以及 [常见问题](https://gkd.li/faq/)
          required: true
        - label: 请 **确保** [已有的问题](https://github.com/gkd-kit/gkd/issues?q=is%3Aissue) 中没有人提交过相似issue，否则请在已有的issue下进行讨论
          required: true
        - label: 请 **务必** 给issue填写一个简洁明了的标题，以便他人快速检索
          required: true
        - label: 请 **确保** 你的问题能在 [releases](https://github.com/gkd-kit/gkd/releases/latest) 发布的最新版本(包含测试版本)上复现 (如果不是请先更新到最新版本复现后再提交问题)
          required: true
        - label: 请 **确保** 提供下列的日志和BUG描述及其复现步骤, 否则你的问题将会被直接关闭
          required: true
  - type: textarea
    id: log-file
    attributes:
      label: |
        日志文件-无论什么问题不包含日志将会被直接关闭
      description: |
        主页-设置-日志, 上传日志文件或者生成链接并粘贴到下面的输入框\
        无论什么问题,你都需要提供日志文件. 没有日志, 纯发文字/截图/视频都是没有用的\
    validations:
      required: true
  - type: textarea
    id: bug-1
    attributes:
      label: |
        BUG描述(文字/截图/视频)
      description: |
        请使用尽量准确的描述, 否则你的问题将会被直接关闭\
        另外如果你的问题是关于快照/选择器的, 请必须提供快照链接或者快照文件, 否则你的问题将会被直接关闭
    validations:
      required: true
  - type: textarea
    id: bug-2
    attributes:
      label: |
        期望行为(文字/截图/视频)
      description: |
        请使用尽量准确的描述, 否则你的问题将会被直接关闭
    validations:
      required: true
  - type: textarea
    id: bug-3
    attributes:
      label: |
        实际行为(文字/截图/视频)
      description: |
        请使用尽量准确的描述, 否则你的问题将会被直接关闭
    validations:
      required: true

