name: 功能请求 / Feature request
title: "[Feature] "
description: 提出你的功能请求 / Propose your feature request
labels: ["enhancement"]

body:
  - type: markdown
    attributes:
      value: |
        感谢您对该项目的兴趣，并花点时间填写此功能请求报告
  - type: checkboxes
    id: checkboxes
    attributes:
      label: 一些验证
      description: 在提交问题之前，请确保您完成以下操作
      options:
        - label: GKD 默认不提供任何规则, 你可以查看 [GKD 官方文档](https://gkd.li) 后自行编写规则或者导入远程订阅, 请不要再提出类似想要XXX规则这种问题 
          required: true
        - label: 请 **确保** 您已经查阅了 [GKD 官方文档](https://gkd.li) 以及 [常见问题](https://gkd.li/faq/)
          required: true
        - label: 请 **确保** [已有的问题](https://github.com/gkd-kit/gkd/issues?q=is%3Aissue) 中没有人提交过相似issue，否则请在已有的issue下进行讨论
          required: true
        - label: 请 **务必** 给issue填写一个简洁明了的标题，以便他人快速检索
          required: true
        - label: 请 **确保** 你想要的功能在 [releases](https://github.com/gkd-kit/gkd/releases/latest) 发布的最新版本(包含测试版本)上没有找到 (如果不是请先更新到最新版本验证后再提交问题)
          required: true
  - type: textarea
    id: feature-description
    attributes:
      label: |
        新功能描述
      description: |
        例如: 我希望在 GKD 中的什么页面添加什么功能, 以及这个功能的作用是什么\
        或者在规则定义中添加某个字段, 以及这个字段的作用是什么\
        请使用准确的描述, 否则你的问题将会被直接关闭
    validations:
      required: true
